# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 608fa12253496b336948416f9b13a0e327e5b33d09b77c7957de80105aa4be6eafadd442247e544b085a29af23e9fee977bf871acc267eacbc31f98dda7c3f7a

test:
  secret_key_base: f16d4226b6b63eb2e6ee14a6f34667f9e826216e441da109ad654697d18191d6d1b9d8aef4f0640a1e52ba9a257f39446b534db9c49b6a1de13af83ffd23c8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
